### ISSUE TITLE
[FEATURE] Support partitioning information for external consumers

### ISSUE THREAD

**Issue by george-zubrienko** [SneaksAndData/arcane-framework#113]
### Description

Currently Arcane does provide `data` and `schema` for each streaming source. However, quite often it is important to also know partitioning info so consumers can update targets incrementally to avoid performance bottlenecks.

### Possible solution

Add optional `partitions` field to stream YAML:

```yaml
partitions:
  - name: date
     field_name: my_column_with_date
     field_format: datetime
  - name: sales_organisation
     field_name: my_column_with_sales_org
     field_format: string
```

In this case, when a streaming runner starts, Arcane should create additional folder `metadata` with a file `partitions.json` in it that contains the information above. CRUD on this field in YAML must be mirrored to the folder.

This will allow external consumers to take advantage of partitioning info for the source specified by the user.
